<?php

namespace Custom\WebBundle;

use Topxia\WebBundle\TopxiaWebBundle as BaseBundle;

class CustomWebBundle extends BaseBundle
{
    public function getEnabledExtensions()
    {
        return parent::getEnabledExtensions(); // TODO: Change the autogenerated stub
    }
}
