<?php

namespace Mooc\WebBundle;

use Topxia\WebBundle\TopxiaWebBundle as BaseBundle;

class MoocWebBundle extends BaseBundle
{
    public function getEnabledExtensions()
    {
        return parent::getEnabledExtensions(); // TODO: Change the autogenerated stub
    }
}
