<?php

namespace CustomBundle\Biz;

use Biz\BaseTestCase;

class CustomTestCase extends BaseTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->biz->register(new CustomServiceProvider());
    }

}
