// 全局
export const GET_SETTINGS = 'GET_SETTINGS';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const GET_CSRF_TOKEN = 'GET_CSRF_TOKEN';
export const GET_CREATE_MARKETING_URL = 'GET_CREATE_MARKETING_URL';

// 课程分类
export const GET_COURSE_CATEGORIES = 'GET_COURSE_CATEGORIES';

// 班级分类
export const GET_CLASS_CATEGORIES = 'GET_CLASS_CATEGORIES';

// 题库分类
export const GET_ITEM_BANK_CATEGORIES = 'GET_ITEM_BANK_CATEGORIES';

// 草稿配置数据
export const UPDATE_DRAFT = 'UPDATE_DRAFT';
