<?php

namespace ApiBundle;

use ApiBundle\Api\Util\UserAssociateUtil;
use Biz\BaseTestCase;

class ApiTestCase extends BaseTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stubUserAssoc();
    }

    private function stubUserAssoc()
    {
        $biz = $this->getBiz();
        $userAssocUtilStub = $this->createMock(UserAssociateUtil::class);
        $userAssocUtilStub->method('single')
            ->willReturn('do nothing');
        $userAssocUtilStub->method('multiple')
            ->willReturn('do nothing');

        $biz['api.util.userAssoc'] =$userAssocUtilStub;
    }
}