<?php

namespace ApiBundle;

use ApiBundle\Api\Util\ObjectCombinationUtil;
use Biz\BaseTestCase;
use Mockery;

class ApiTestCase extends BaseTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stubUserAssoc();
    }

    private function stubUserAssoc()
    {
        $biz = $this->getBiz();

        $stub = Mockery::mock(ObjectCombinationUtil::class);
        $stub->shouldReceive('single');
        $stub->shouldReceive('multiple');

        $biz['api.util.oc'] = $stub;
    }
}