<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131204095105 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSQL("
    		ALTER TABLE  `user` CHANGE  `approvalTime`  `approvalTime` INT( 10 ) NOT NULL DEFAULT  '0' COMMENT  '认证时间';
    		");
        $this->addSQL("
            ALTER TABLE  `user_profile` CHANGE  `idcard`  `idcard` VARCHAR( 24 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '0' COMMENT '身份证号码';
            ");
        $this->addSQL("
            ALTER TABLE  `user_profile` CHANGE  `truename`  `truename` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' '';
            ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
