<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130722172838 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `content` ADD  `promoted` TINYINT UNSIGNED NOT NULL DEFAULT  '1' COMMENT  '在列表中是否显示该条目。' AFTER  `featured`;");
    	$this->addSql("ALTER TABLE  `content` ADD  `sticky` TINYINT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '是否置顶' AFTER  `promoted`");
        $this->addSql("ALTER TABLE  `content` CHANGE  `updatedTime`  `publishedTime` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
