<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140109121415 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `mysale_product` RENAME `mysale` ");

         $this->addSql("ALTER TABLE  `mysale_log` RENAME `mysale_visitor` ");

         $this->addSql("ALTER TABLE  `mysale` CHANGE  `userId`  `userId` int(11) NOT NULL  DEFAULT  '0' COMMENT '渠道Id' ");

         $this->addSql("ALTER TABLE  `mysale` ADD  `managerId`  int(11) NOT NULL  DEFAULT  '0' COMMENT '管理人员Id' ");

         $this->addSql("ALTER TABLE  `mysale_order` CHANGE  `mId`  `mysaleId` int(11) NOT NULL  DEFAULT  '0' COMMENT '推广Id' ");

         $this->addSql("ALTER TABLE  `mysale_visitor` CHANGE  `mId`  `mysaleId` int(11) NOT NULL  DEFAULT  '0' COMMENT '推广Id' ");

         $this->addSql("ALTER TABLE  `mysale_visitor` CHANGE  `userId`  `visitorId` int(11) NOT NULL  DEFAULT  '0' COMMENT '访问用户Id' ");

         $this->addSql("ALTER TABLE  `mysale_visitor` ADD  `visitorInfo`  text  CHARACTER SET utf8 COMMENT '客户端信息'  AFTER  `userIp` ");

         $this->addSql("ALTER TABLE  `course_order` ADD  `mTookeen` VARCHAR( 1024 )  DEFAULT NULL COMMENT  '渠道mTookeen'  AFTER  `promoCode` ");


         


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
