<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130923151721 extends AbstractMigration
{
    public function up(Schema $schema)
    {
		$this->addSql("
			ALTER TABLE  `course_member` ADD  `remarks` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  '备注' AFTER  `seq`
			");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
