<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130708111742 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `course` CHANGE  `status`  `status` ENUM(  'draft',  'published',  'closed' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'draft' COMMENT  '课程状态'");
        $this->addSql("ALTER TABLE  `course` CHANGE  `memberNum`  `studentNum` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
