<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130826095728 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("
			CREATE TABLE IF NOT EXISTS `user_disk_file` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `userId` int(11) NOT NULL,
			  `filepath` varchar(2048) NOT NULL,
			  `filename` varchar(1024) NOT NULL,
			  `uri` varchar(1024) NOT NULL,
			  `isDirectory` tinyint(1) NOT NULL DEFAULT '0',
			  `size` int(11) NOT NULL DEFAULT '0',
			  `mimeType` varchar(255) NOT NULL,
			  `etag` varchar(128) NOT NULL,
			  `type` enum('document','video','audio','image','other') NOT NULL DEFAULT 'other',
			  `storage` enum('local','cloud') NOT NULL,
			  `bucket` varchar(255) NOT NULL,
			  `updatedTime` int(10) unsigned NOT NULL,
			  `createdTime` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
