<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106175003 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("	ALTER TABLE  `activity_member` ADD  `joinMode`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '直播' COMMENT  '参与方式：直播|现场|到时候再决定'  AFTER  `orderId`");

        $this->addSql(" ALTER TABLE  `activity` CHANGE  `price`   `price` float(10,2) NOT NULL DEFAULT '0.00' COMMENT  '线下价格：0表示免费 大于99999表示多种票 大于0小于99999单一票'  ");

         $this->addSql(" ALTER TABLE  `activity` ADD  `onlinePriceMode`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '免费' COMMENT  '线上价格模式:免费|单一价|多种价'  AFTER  `onlinePrice`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
