<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131105133024 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("
       
            ALTER TABLE  `activity` ADD  `duration`  VARCHAR( 255 )  DEFAULT NULL COMMENT  '时长'    AFTER  `endTime`
            ");

          $this->addSql("

            ALTER TABLE  `activity` ADD  `type`  enum('openclass','training') NOT NULL DEFAULT 'openclass' COMMENT '活动类型'    AFTER  `subtitle`
            ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
