<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140415234431 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE `article` DROP `hasPicture`;");
    	$this->addSql("ALTER TABLE `article` CHANGE `picture` `thumb` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';");
    	$this->addSql("ALTER TABLE `article` ADD `originalThumb` VARCHAR(255) NOT NULL COMMENT '缩略图原图' AFTER `thumb`;");
    	$this->addSql("ALTER TABLE `article` ADD `picture` VARCHAR(255) NOT NULL COMMENT '文章添加/编辑时，如文章中有图片保存' AFTER `originalThumb`;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
