<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131030004353 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        // this up() migration is autogenerated, please modify it to your needs
        
         $this->addSql("ALTER TABLE  `course_order` ADD  `prodType` VARCHAR( 255 ) NOT NULL DEFAULT 'course' COMMENT  '商品类型'  AFTER  `title`");

         $this->addSql("ALTER TABLE  `course_order` ADD  `prodId` INT(10) NOT NULL  DEFAULT '0' COMMENT  '商品Id,不包括课程Id'  AFTER  `courseId`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
