<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140124023325 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("RENAME TABLE  `test_item` TO  `testpaper_item` ;");
        $this->addSql("RENAME TABLE  `test_item_result` TO  `testpaper_item_result` ;");
        $this->addSql("RENAME TABLE  `test_paper` TO  `testpaper` ;");
        $this->addSql("RENAME TABLE  `test_paper_result` TO  `testpaper_result` ;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
