<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140111191509 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
          $this->addSql("ALTER TABLE  `course` ADD  `saleValidTime` int(11)  DEFAULT '0' COMMENT  '销售有效期'  AFTER  `expiryDay` ");

          $this->addSql("ALTER TABLE  `course` ADD  `commissionType` varchar(24)  DEFAULT NULL COMMENT  '佣金类型 固定|比例'  AFTER  `saleValidTime` ");

          $this->addSql("ALTER TABLE  `course` ADD  `commission` float(10,2)  DEFAULT '0.00' COMMENT  '佣金数字 '  AFTER  `commissionType` ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
