<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140128170801 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

         $this->addSql("ALTER TABLE  `sale_offsale` CHANGE  `adCommission`  `adCommission`  float(10,2)  NOT NULL COMMENT  '佣金额度'  AFTER  `adCommissionType` ");

         $this->addSql("ALTER TABLE  `sale_mysale` CHANGE  `userId`  `partnerId`  int(11)  NOT NULL COMMENT  '渠道ID'   ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
