<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130723114711 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `user_profile` ADD  `weibo` VARCHAR( 255 ) NOT NULL");
    	$this->addSql("ALTER TABLE  `user_profile` ADD  `blog` VARCHAR( 255 ) NOT NULL");
    	$this->addSql("ALTER TABLE  `user_profile` ADD  `site` VARCHAR( 255 ) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
