<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131216223942 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	$this->addSql("
		CREATE TABLE IF NOT EXISTS `quiz_question` (
			  `id` bigint(20) NOT NULL AUTO_INCREMENT,
			  `questionType` enum('choice','single_choice','fill','material','essay','determine') NOT NULL,
			  `stem` text NOT NULL COMMENT '题干',
			  `score` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分数',
			  `answer` text NOT NULL COMMENT '参考答案',
			  `analysis` text COMMENT '解析',
			  `categoryId` int(11) NOT NULL DEFAULT '0' COMMENT '类别',
			  `difficulty` enum('simple','ordinary','difficulty') NOT NULL,
			  `targetId` int(11) NOT NULL COMMENT '从属于',
			  `targetType` enum('lesson','course','subject') NOT NULL COMMENT '从属类型：课时、课程、科目',
			  `parentId` int(10) unsigned DEFAULT '0' COMMENT '材料父ID',
			  `finishedTimes` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '完成次数',
			  `passedTimes` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '成功次数',
			  `userId` int(11) NOT NULL COMMENT '用户id',
			  `updatedTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
			  `createdTime` int(10) unsigned NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='问题表' AUTO_INCREMENT=101 ;


			CREATE TABLE IF NOT EXISTS `quiz_question_category` (
			  `id` int(11) NOT NULL AUTO_INCREMENT,
			  `name` varchar(255) NOT NULL COMMENT '类别名称',
			  `targetId` int(11) NOT NULL COMMENT '从属课程、科目id',
			  `targetType` enum('course','subject','lesson') NOT NULL COMMENT '从属课程、科目',
			  `userId` int(11) NOT NULL COMMENT '操作用户',
			  `updatedTime` int(11) NOT NULL COMMENT '更新时间',
			  `createdTime` int(11) NOT NULL COMMENT '创建时间',
			  `seq` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='题库类别表' AUTO_INCREMENT=27 ;


			CREATE TABLE IF NOT EXISTS `quiz_question_choice` (
			  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
			  `questionId` bigint(20) NOT NULL COMMENT 'quesitonId',
			  `content` text NOT NULL COMMENT 'content',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=118 ;
		");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
