<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106203502 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("	ALTER TABLE  `activity_member` CHANGE  `joinMode`  `joinMode`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '线上' COMMENT  '参与方式：线上|线下|到时候再决定'  AFTER  `orderId`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
