<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130721140833 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `content` ADD  `picture` VARCHAR( 255 ) NOT NULL AFTER  `body`");
        $this->addSql("ALTER TABLE  `content` ADD  `template` VARCHAR( 255 ) NOT NULL AFTER  `picture`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
