<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140114165548 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("ALTER TABLE  `mysale_commission` ADD  `updatedTime` int(11)   NOT NULL  DEFAULT '0'  COMMENT  '最后一次操作时间'  AFTER  `status` ");

        $this->addSql("ALTER TABLE  `mysale_commission` ADD  `drawedTime` int(11)  NOT NULL  DEFAULT '0'  COMMENT  '取款时间'  AFTER  `updatedTime` ");

        $this->addSql("ALTER TABLE  `mysale_commission` ADD  `paidTime` int(11)    NOT NULL  DEFAULT '0'   COMMENT  '订单支付时间'  AFTER  `drawedTime` ");

        $this->addSql("ALTER TABLE  `mysale_commission`  ADD  `note` VARCHAR( 1024 )  DEFAULT NULL COMMENT  '备注说明'  AFTER  `commission` ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
