<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131013112324 extends AbstractMigration
{
    public function up(Schema $schema)
    {
		$this->addSql("DROP TABLE upgradeBackup;");
		$this->addSql("DROP TABLE packages;");
		$this->addSql("DROP TABLE upgradeLogs;");
    
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
