<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131111100606 extends AbstractMigration
{

    public function up(Schema $schema)
    {
    	$this->addSql("INSERT INTO `category_group` (`id`, `code`, `name`, `depth`) VALUES (NULL, 'course', '课程分类', '1');");
    	$this->addSql("INSERT INTO `migration_versions` (`version`) VALUES ('20131015165757');");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
