<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131126161847 extends AbstractMigration
{
    public function up(Schema $schema)
    {
         // this up() migration is autogenerated, please modify it to your needs
         // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `offsale` CHANGE  `reuse`  `reuse` varchar(24) CHARACTER SET utf8  DEFAULT '不可以' NOT NULL COMMENT '可重复使用：可以/不可以' 
            ");
         $this->addSql("ALTER TABLE  `offsale` CHANGE  `valid`  `valid` varchar(24) CHARACTER SET utf8  DEFAULT '有效' NOT NULL COMMENT '是否有效：有效/无效'
            ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
