<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140617110851 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE `course` CHANGE `homeworkCompleteLimit` `homeworkCompleteLimit` ENUM('inherited','yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'inherited';");
        $this->addSql("ALTER TABLE `homework` CHANGE `completeLimit` `completeLimit` ENUM('inherited','yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'inherited' COMMENT '作业限制是否必须完成';");
        

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
