<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140401114137 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
            DROP TABLE IF EXISTS `member`;
            CREATE TABLE `member` (
              `id` int(10) NOT NULL AUTO_INCREMENT,
              `userId` int(10) NOT NULL,
              `levelId` int(10) unsigned NOT NULL,
              `deadline` int(10) unsigned NOT NULL,
              `boughtType` enum('new','upgrade','renew','edit') NOT NULL COMMENT '购买类型',
              `boughtTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '购买时间',
              `boughtDuration` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '购买时长',
              `boughtUnit` enum('month','year') NOT NULL COMMENT '开通方式按月、按年',
              `boughtAmount` float(10,2) NOT NULL DEFAULT '0.00',
              `orderId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '购买会员的订单ID',
              `operatorId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '管理员操作时为管理员用户ID',
              `createdTime` int(10) DEFAULT '0',
              PRIMARY KEY (`id`),
              UNIQUE KEY `userId` (`userId`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='会员表';


            DROP TABLE IF EXISTS `member_history`;
            CREATE TABLE `member_history` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `userId` int(10) unsigned NOT NULL COMMENT '购买用户',
              `levelId` int(10) unsigned NOT NULL COMMENT '会员类型',
              `deadline` int(10) unsigned NOT NULL,
              `boughtType` enum('new','upgrade','renew','edit','cancel') NOT NULL COMMENT '购买类型',
              `boughtTime` int(10) unsigned NOT NULL,
              `boughtDuration` int(10) unsigned NOT NULL,
              `boughtUnit` enum('none','month','year') NOT NULL DEFAULT 'none',
              `boughtAmount` float(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '购买金额',
              `orderId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '购买会员的订单ID',
              `operatorId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '管理员操作时为管理员用户ID',
              `createdTime` int(10) unsigned NOT NULL,
              PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='会员记录表';
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
