<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131105152519 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        // this up() migration is autogenerated, please modify it to your needs
           
           // this up() migration is autogenerated, please modify it to your needs
           $this->addSql("ALTER TABLE  `activity` CHANGE  `experterId`  `expertersId` text CHARACTER SET utf8 NOT NULL COMMENT '专家' 
            ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
