<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131012093721 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
    		ALTER TABLE  `activity_member` CHANGE  `aboutinfo`  `aboutInfo` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  '说点什么';
    		");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
