<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131121113041 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("                
                CREATE TABLE IF NOT EXISTS `offsale` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                  `prodType` varchar( 256 ) CHARACTER SET utf8 DEFAULT '课程' COMMENT '优惠商品类型',  
                  `prodId` int(10) NOT NULL COMMENT '优惠商品Id',
                  `promoCode` varchar( 256 ) CHARACTER SET utf8 DEFAULT NULL COMMENT '优惠码，唯一值',                  
                  `reducePrice` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠价格',
                  `validTime` int(10) unsigned NOT NULL COMMENT '截止日期',
                  `reuse` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0：不可以，1：可以，可否可重复使用',
                  `valid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0：不可用，1：可用，是否可用',
                  `createdTime` int(10) unsigned NOT NULL COMMENT '创建时间',
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='' AUTO_INCREMENT=1 ;
                ");

        $this->addSql("ALTER TABLE  `course_order` ADD  `promoCode` VARCHAR( 256 )  DEFAULT NULL COMMENT  '使用的优惠码'  AFTER  `sn`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
