<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130813095901 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("
			CREATE TABLE IF NOT EXISTS `log` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `userId` int(10) unsigned NOT NULL DEFAULT '0',
			  `module` varchar(32) NOT NULL,
			  `action` varchar(32) NOT NULL,
			  `message` text NOT NULL,
			  `ip` varchar(255) NOT NULL,
			  `createdTime` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `userId` (`userId`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
