<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140409131043 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `course` ADD  `showCourseStatus` ENUM('unserialize',  'serialize',  'finished' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'unserialize' AFTER  `showStudentNumType`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
