<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131226140235 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
       $this->addSql("
		    CREATE TABLE IF NOT EXISTS `mysale_product` (
			  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
			  `prodType` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT '商品类型',
			  `prodId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品Id',
			  `commission` float(11,2) NOT NULL DEFAULT '0.00' COMMENT '佣金',
			  `mTookeen` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT 'mtookeen',
			  `tUrl` text NOT NULL COMMENT '推广链接地址',
			  `validTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '有效时间',
			  `userId` int(11) NOT NULL COMMENT '用户id',
			  `updatedTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
			  `createdTime` int(11) unsigned NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='推广表'  AUTO_INCREMENT=1;


			CREATE TABLE IF NOT EXISTS `mysale_order` (
			  `id` int(11) unsigned  NOT NULL AUTO_INCREMENT,
			  `mId` varchar(255) CHARACTER SET utf8  NOT NULL COMMENT '推广id',
			  `mTookeen` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT 'mTookeen',
			  `buyerId` int(11) NOT NULL COMMENT '购买人Id',
			  `orderId` int(11) NOT NULL COMMENT '订单Id',
			  `orderSn` varchar(255)  CHARACTER SET utf8  NOT NULL COMMENT '订单sn',
			  `commission` float(11,2) NOT NULL DEFAULT '0.00' COMMENT '本笔订单佣金收入',
			  `status` varchar(255)  CHARACTER SET utf8  NOT NULL COMMENT '成交记录状态',
			  `paidTime` int(11) NOT NULL COMMENT '更新时间',
			  `createdTime` int(11) NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='推广成交记录表'  AUTO_INCREMENT=1;


			CREATE TABLE IF NOT EXISTS `mysale_log` (
			  `id` int(11) unsigned  NOT NULL AUTO_INCREMENT,
			  `mId` varchar(255) CHARACTER SET utf8  NOT NULL COMMENT '推广id',
			  `userId` int(11) NOT NULL COMMENT '访问人Id',
			  `mTookeen` varchar(255) CHARACTER SET utf8  NOT NULL COMMENT '推广标示',
			  `uTookeen` varchar(255) CHARACTER SET utf8  NOT NULL COMMENT '访客标示',
			  `userIp` varchar(255) CHARACTER SET utf8  NOT NULL COMMENT '访客Ip',
			  `createdTime` int(11) NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='推广记录流量日志表'  AUTO_INCREMENT=1;


		
		");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
