<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131203180008 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSQL("
    		ALTER TABLE  `user_approval` CHANGE  `idcard`  `idcard` VARCHAR( 24 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '0' COMMENT '身份证号';
    	");
        $this->addSQL("
            ALTER TABLE  `user_approval` CHANGE  `faceImg`  `faceImg` VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  ' ' ;
        ");
        $this->addSQL("
            ALTER TABLE  `user_approval` CHANGE  `backImg`  `backImg` VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  ' ' ;
        ");
        $this->addSQL("
           ALTER TABLE  `user_approval` CHANGE  `createdTime`  `createdTime` INT( 10 ) NOT NULL DEFAULT  '0' COMMENT  '申请时间';
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
