<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140113111945 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `mysale_order` RENAME `mysale_commission` ");

         $this->addSql("ALTER TABLE  `mysale_commission` CHANGE  `status`  `status`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT '佣金提取状态 created,paid,applying,refused,cancelled' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
