<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140511224227 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("ALTER TABLE  `business_state` ADD  `totalOrders`  int(10) NOT NULL DEFAULT '0'  COMMENT '总订单' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `totalFeeOrders`  int(10) NOT NULL DEFAULT '0'  COMMENT '总收费订单' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `totalFreeOrders`  int(10) NOT NULL DEFAULT '0'  COMMENT '总免费订单' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
