<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130717173134 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
			CREATE TABLE IF NOT EXISTS `content` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `title` varchar(255) NOT NULL,
			  `type` varchar(255) NOT NULL,
			  `alias` varchar(255) NOT NULL,
			  `summary` text NOT NULL,
			  `body` text NOT NULL,
			  `status` enum('published','unpublished','trash') NOT NULL,
			  `categoryId` int(10) unsigned NOT NULL DEFAULT '0',
			  `tags` tinytext NOT NULL,
			  `hits` int(10) unsigned NOT NULL DEFAULT '0',
			  `featured` int(10) unsigned NOT NULL DEFAULT '0',
			  `userId` int(10) unsigned NOT NULL,
			  `field1` text NOT NULL,
			  `field2` text NOT NULL,
			  `field3` text NOT NULL,
			  `field4` text NOT NULL,
			  `field5` text NOT NULL,
			  `field6` text NOT NULL,
			  `field7` text NOT NULL,
			  `field8` text NOT NULL,
			  `field9` text NOT NULL,
			  `field10` text NOT NULL,
			  `updatedTime` int(10) unsigned NOT NULL DEFAULT '0',
			  `createdTime` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
    	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
