<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106173211 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
       $this->addSql("	ALTER TABLE  `activity`  ADD    `onlinePrice`  float(10,2)  NOT NULL DEFAULT '0.00' COMMENT  '线上价格:0表示免费 大于99999表示多种票 大于0小于99999单一票'  AFTER `price` ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
