<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131017104113 extends AbstractMigration
{
    public function up(Schema $schema)
    {
  		$this->addSql("ALTER TABLE  `installed_packages` DROP  `installlog`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
