<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130809153710 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE `user` DROP `unreadNotificationNum`");
        $this->addSql("ALTER TABLE  `user` ADD  `newMessageNum` INT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `loginIp`");
        $this->addSql("ALTER TABLE  `user` ADD  `newNotificationNum` INT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `newMessageNum`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
