<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131126110140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("       
            ALTER TABLE  `offsale` ADD  `prodName`  varchar(256)  CHARACTER SET utf8 COMMENT '商品名称'  AFTER  `prodId` 
            ");

        $this->addSql("       
            ALTER TABLE  `offsale` ADD  `promoName`  varchar(256)  CHARACTER SET utf8 COMMENT '优惠码名称'  AFTER  `prodName` 
            ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
