<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140421221701 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        // 
        $this->addSql("
            DROP TABLE IF EXISTS `article`;
            CREATE TABLE IF NOT EXISTS `article` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `title` varchar(255) NOT NULL COMMENT '文章标题',
              `categoryId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '栏目',
              `tagIds` tinytext COMMENT 'tag标签',
              `source` varchar(1024) DEFAULT '' COMMENT '来源',
              `sourceUrl` varchar(1024) DEFAULT '' COMMENT '来源URL',
              `publishedTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发布时间',
              `body` text,
              `thumb` varchar(255) NOT NULL DEFAULT '',
              `originalThumb` varchar(255) NOT NULL DEFAULT '' COMMENT '缩略图原图',
              `picture` varchar(255) NOT NULL DEFAULT '' COMMENT '文章添加/编辑时，如文章中有图片保存',
              `status` enum('published','unpublished','trash') NOT NULL DEFAULT 'unpublished' COMMENT '状态',
              `hits` int(10) unsigned NOT NULL DEFAULT '0',
              `featured` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '头条',
              `promoted` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '推荐',
              `sticky` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否置顶',
              `userId` int(10) unsigned NOT NULL DEFAULT '0',
              `createdTime` int(10) unsigned NOT NULL DEFAULT '0',
              `updatedTime` int(10) unsigned NOT NULL DEFAULT '0',
              PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
        ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
