<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130730183206 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `course_lesson` ADD  `materialNum` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '上传的资料数量' AFTER  `length`");
    	$this->addSql("ALTER TABLE  `course_lesson` ADD  `quizNum` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '测验题目数量' AFTER  `materialNum`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}