<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140114155446 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

          $this->addSql("ALTER TABLE  `mysale` ADD  `adCommissionType` varchar(24)  DEFAULT NULL COMMENT  '渠道佣金类型 ratio|quota'  AFTER  `prodName` ");

          $this->addSql("ALTER TABLE  `mysale` CHANGE  `commission` `adCommission` float(10,2)  DEFAULT '0.00' COMMENT  '佣金数字 '  AFTER  `adCommissionType` ");


          $this->addSql("ALTER TABLE  `mysale_commission` CHANGE  `userId`  `salerId`  int(11)  NOT NULL COMMENT  '佣金所属人'  AFTER  `buyerId` ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
