<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140109160220 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `user` ADD  `level` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '用户会员等级' AFTER  `salt`");
    	$this->addSql("ALTER TABLE  `user` ADD  `levelDeadline` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '用户会员等级期限' AFTER  `level`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
