<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131118230737 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE  `money_card` CHANGE  `rechargeStatus`  `cardStatus` ENUM(  'normal',  'invalid',  'recharged' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;");
        $this->addSql("ALTER TABLE  `money_card` CHANGE  `validTime`  `deadline` VARCHAR( 19 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  '有效时间';");
        $this->addSql("ALTER TABLE  `money_card_batch` DROP  `cardStatus` ;");
        $this->addSql("ALTER TABLE  `money_card_batch` CHANGE  `validTime`  `deadline` VARCHAR( 19 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
