<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140226164955 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("ALTER TABLE `user_approval` DROP `educations`;");
        $this->addSql("ALTER TABLE `user_approval` DROP `careers`;");
        $this->addSql("ALTER TABLE `user_approval` DROP `skills`;");
        $this->addSql("ALTER TABLE `user_approval` DROP `purpose`;");
        $this->addSql("ALTER TABLE `user_approval` DROP `resume`;");

        $this->addSql("CREATE TABLE IF NOT EXISTS `user_resume` (
				  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
				  `userId` int(11) unsigned NOT NULL,
				  `createdTime` int(10) unsigned NOT NULL,
				   PRIMARY KEY (`id`)
				) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;");

        $this->addSql("ALTER TABLE  `user_resume` ADD  `educations`   TEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '教育经历'  AFTER  `userId`");

        $this->addSql("ALTER TABLE  `user_resume` ADD  `careers`   TEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '工作经历'  AFTER  `educations`");

        $this->addSql("ALTER TABLE  `user_resume` ADD  `skills`   TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '擅长技能'  AFTER  `careers`");

        $this->addSql("ALTER TABLE  `user_resume` ADD  `purpose`   TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '求职需求'  AFTER  `skills`");

        $this->addSql("ALTER TABLE  `user_resume` ADD  `resume`   VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '简历'  AFTER  `skills`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
