<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130815171356 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	$this->addSQL("
			ALTER TABLE  `user_profile` CHANGE  `blog`  `weixin` VARCHAR( 255 )  NOT NULL;
    	");
        // this up() migration is autogenerated, please modify it to your needs

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
