<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131009174124 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	$this->addSql("
    		CREATE TABLE `upgradeBackup` (
			  `id` int(11) NOT NULL AUTO_INCREMENT,
			  `type` enum('database','directory') NOT NULL COMMENT '备份类型，database是数据库备份，directory是文件夹备份',
			  `fileId` int(11) NOT NULL COMMENT '备份处理并上传后的文件ID',
			  `ename` varchar(255) NOT NULL COMMENT '英文名',
			  `cname` varchar(255) NOT NULL COMMENT '中文名',
			  `version` varchar(255) NOT NULL COMMENT '当前安装的版本',
			  `createdTime` int(11) NOT NULL COMMENT '备份时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='这张表只针对软件包升级而备份';
    	");

    	$this->addSql("
			INSERT INTO  `file_group` (`id` ,`name` ,`code` ,`public`) VALUES (null,  '升级包备份',  'upgradeBackup',  '1');
    	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
