<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140318171410 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("
			CREATE TABLE `member` (
			  `id` int(10) NOT NULL AUTO_INCREMENT,
			  `userId` int(10) NOT NULL,
			  `levelId` int(3) NOT NULL,
			  `deadline` int(10) unsigned NOT NULL,
			  `createTime` int(10) DEFAULT '0',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='会员表';
		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
