<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140403100017 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `order_refund` ADD  `targetType` VARCHAR( 64 ) NOT NULL DEFAULT  '' AFTER  `userId`;");
        $this->addSql("ALTER TABLE  `order_refund` CHANGE  `courseId`  `targetId` INT( 10 ) UNSIGNED NOT NULL;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
