<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140303205438 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

          $this->addSql("ALTER TABLE  `sale_linksale` ADD  `linkName`   VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '备注描述'  AFTER  `prodName`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
