<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130927151140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `course_member` ADD  `orderId` INT UNSIGNED NOT NULL COMMENT  '学员购买课程时的订单ID' AFTER  `userId`");
        $this->addSql("ALTER TABLE  `course_member` ADD  `locked` TINYINT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `role`");
        $this->addSql("ALTER TABLE  `course_order` CHANGE  `status`  `status` ENUM(  'created',  'paid',  'refunding',  'refunded',  'cancelled' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;");
        $this->addSql("ALTER TABLE  `course_order` ADD  `refundId` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '最后一次退款操作记录的ID' AFTER  `giftTo`");
        $this->addSql("
            CREATE TABLE `course_order_refund` (
            `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
            `orderId` int(10) unsigned NOT NULL,
            `userId` int(10) unsigned NOT NULL,
            `courseId` int(10) unsigned NOT NULL,
            `status` enum('created','success','failed','cancelled') NOT NULL DEFAULT 'created',
            `expectedAmount` float(10,2) unsigned DEFAULT '0.00' COMMENT '期望退款的金额，NULL代表未知，0代表不需要退款',
            `actualAmount` float(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '实际退款金额，0代表无退款',
            `reasonType` varchar(64) NOT NULL,
            `reasonNote` varchar(1024) NOT NULL,
            `createdTime` int(10) unsigned NOT NULL,
            UNIQUE KEY `id` (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
        ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
