<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140106102940 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("
    		CREATE TABLE IF NOT EXISTS `course_coupon` (
			  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
			  `code` varchar(255) CHARACTER SET utf8 NOT NULL,
			  `type` enum('minus','discount') NOT NULL COMMENT '优惠方式',
			  `rate` float(10,2) unsigned NOT NULL COMMENT '优惠额度 若优惠方式为折扣，则为折扣率，若为立减，则为减免金额',
			  `status` enum('unused','used') NOT NULL DEFAULT 'unused' COMMENT '优惠码状态',
			  `times` int(10) unsigned NOT NULL COMMENT '可使用次数',
			  `targetType` varchar(255) NOT NULL DEFAULT '',
			  `targetId` int(11) unsigned NOT NULL DEFAULT '0',
			  `orderId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '订单号',
			  `orderUserId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '使用人',
			  `orderTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '使用时间',
			  `deadline` int(10) unsigned NOT NULL COMMENT '过期时间',
			  `createdTime` int(10) unsigned NOT NULL COMMENT '生成时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
    	");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}



