<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140120203857 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE `question_favorite` ADD `targetType` VARCHAR(255) NOT NULL DEFAULT '' AFTER `questionId`;");
    	$this->addSql("ALTER TABLE `question_favorite` ADD `targetId` INT NOT NULL DEFAULT '0' AFTER `targetType`;");
    	$this->addSql("ALTER TABLE `question_favorite` DROP `testPaperResultId`;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
