<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130926151743 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `user` ADD  `setup` TINYINT NOT NULL DEFAULT  '1' COMMENT  '是否初始化设置的，未初始化的可以设置邮箱、昵称。' AFTER  `emailVerified`");
    }

    public function down(Schema $schema)
    {
        
        // this down() migration is autogenerated, please modify it to your needs

    }
}
