<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140108120047 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql(" ALTER TABLE  `user_approval` ADD  `mobile`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '联系电话'  AFTER  `truename`");

         $this->addSql(" ALTER TABLE  `user_approval` ADD  `email2`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '常用邮箱'  AFTER  `mobile`");

         $this->addSql(" ALTER TABLE  `user_approval` ADD  `postAddr`  VARCHAR( 1024 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '邮寄地址'  AFTER  `email2`");

         $this->addSql(" ALTER TABLE  `user_approval` ADD  `company`  VARCHAR( 1024 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '公司'  AFTER  `postAddr`");

         $this->addSql(" ALTER TABLE  `user_approval` ADD  `job`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '职位'  AFTER  `company`");

         $this->addSql(" ALTER TABLE  `user_approval` ADD  `headImg`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '' COMMENT  '正面免冠人头照'  AFTER  `backImg`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs


    }
}
