<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140630104301 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
        	ALTER TABLE `course` ADD `progressControl` ENUM('noControl','Learned') NOT NULL  DEFAULT 'noControl'  AFTER `maxStudentNum`;
        	ALTER TABLE `course` ADD `learnedCondition` ENUM('noControl','mediaPlayed','homeworkDone') NOT NULL DEFAULT 'noControl' AFTER`progressControl`;
    	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
