<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140312223712 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE `course` DROP `showStudentType`;");

    	$this->addSql("ALTER TABLE  `course` ADD  `showStudentNumType` ENUM(  'opened',  'closed' ) NOT NULL DEFAULT  'opened' AFTER  `expiryDay`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
