<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140502171823 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `user_state` ADD  `createdTime`  int(11) NOT NULL DEFAULT '0'  COMMENT '记录生成时间' ");

        $this->addSql("ALTER TABLE  `guest_state` ADD  `createdTime`  int(11) NOT NULL DEFAULT '0'  COMMENT '记录生成时间' ");

        $this->addSql("ALTER TABLE  `partner_state` ADD  `createdTime`  int(11) NOT NULL DEFAULT '0'  COMMENT '记录生成时间' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `createdTime`  int(11) NOT NULL DEFAULT '0'  COMMENT '记录生成时间' ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
