<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131105144630 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
           $this->addSql("ALTER TABLE  `activity` CHANGE  `type`  `actType` VARCHAR( 255 ) NOT NULL DEFAULT '公开课' COMMENT '活动类型：公开课、培训'    AFTER  `subtitle`
            ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
