<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131119101404 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
  			$this->addSql("
  				CREATE TABLE `user_level` (
				  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
				  `seq` int(11) NOT NULL,
				  `Name` varchar(64) CHARACTER SET utf8 NOT NULL COMMENT '名称',
				  `Icon` varchar(255) CHARACTER SET utf8 NOT NULL COMMENT '图标',
				  `enabled` int(1) NOT NULL COMMENT '状态',
				  `createdTime` int(11) NOT NULL COMMENT '创建时间',
				  PRIMARY KEY (`id`)
				) ENGINE=InnoDB  DEFAULT CHARSET=utf8;");
   
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
