<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131219223817 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSQL("
    		ALTER TABLE  `course` ADD  `expiryDay` INT NOT NULL AFTER  `price`;
    		");

        $this->addSQL("
    		ALTER TABLE  `course_member` ADD  `deadline` INT NOT NULL AFTER  `orderId`
    		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
