<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131206234129 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSQL("
    		alter table `quiz_question` drop column `questionType`;
    		");
    	$this->addSQL("
    		ALTER TABLE `quiz_question` ADD `questionType` enum('choice','single_choice','fill','material','essay','determine') NOT NULL COMMENT '题目类型';
    		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
