<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106155901 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("                
                CREATE TABLE IF NOT EXISTS `activity_price` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                  `activityId` int(10) NOT NULL COMMENT '活动Id',
                  `name` varchar(1024) CHARACTER SET utf8 DEFAULT NULL COMMENT '价格对象',                  
                  `maxNum` int(10) NOT NULL  DEFAULT '0' COMMENT '可售张数',
                  `remainNum` int(10) NOT NULL  DEFAULT '0' COMMENT '剩余张数',
                  `price` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '价格',
                  `unit` varchar(1024) CHARACTER SET utf8 DEFAULT '元/人' COMMENT '单位',
                  `comment` varchar(1024) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注说明',
                  `validTime` int(10) unsigned NOT NULL COMMENT '截止日期',
                  `createdTime` int(10) unsigned NOT NULL COMMENT '创建时间',
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='' AUTO_INCREMENT=1 ;
                ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
