<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140502205423 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `user_state` CHANGE  `totalPv` `dayUserPv`  int(10) NOT NULL DEFAULT '0'  ");

        $this->addSql("ALTER TABLE  `guest_state` CHANGE  `totalPv` `dayGuestPv`  int(10) NOT NULL DEFAULT '0'  ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
