<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131224113116 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `user_level` CHANGE  `Name`  `name` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT  '名称'");
    	$this->addSql("ALTER TABLE  `user_level` CHANGE  `icon`  `icon` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT  '图标'");
    	$this->addSql("ALTER TABLE  `user_level` CHANGE  `enabled`  `enabled` TINYINT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '状态'");
    	$this->addSql("ALTER TABLE  `user_level` ADD  `monthPrice` FLOAT( 10, 2 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '按月购买会员的价格' AFTER  `icon`");
    	$this->addSql("ALTER TABLE  `user_level` ADD  `yearPrice` FLOAT( 10, 2 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '按年购买的价格' AFTER  `monthPrice`");
    	$this->addSql("ALTER TABLE  `user_level` ADD  `description` TEXT NULL DEFAULT NULL COMMENT  '会员的描述信息' AFTER  `yearPrice`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
