<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131117141314 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	 $this->addSql("CREATE TABLE IF NOT EXISTS `money_card` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cardId` varchar(32) NOT NULL,
  `password` varchar(32) NOT NULL,
  `validTime` varchar(19) NOT NULL COMMENT '有效时间',
  `rechargeTime` int(10) NOT NULL COMMENT '充值时间，0为未充值',
  `rechargeStatus` enum('normal','invalid','recharged') NOT NULL,
  `rechargeUserId` int(11) NOT NULL,
  `batchId` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;");

    	 $this->addSql("CREATE TABLE IF NOT EXISTS `money_card_batch` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cardPrefix` varchar(32) CHARACTER SET utf8 NOT NULL,
  `cardMedian` int(8) NOT NULL,
  `number` int(12) NOT NULL,
  `validTime` varchar(19) NOT NULL,
  `cardStatus` enum('normal','invalid') NOT NULL,
  `money` int(8) NOT NULL,
  `createdId` int(11) NOT NULL,
  `createdTime` int(11) NOT NULL,
  `disc` varchar(128) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
