<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140428152040 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `access_log` CHANGE  `accessUri`  `accessHref`  varchar(1024) NOT NULL DEFAULT '' ");
        $this->addSql("ALTER TABLE  `access_log` CHANGE  `accessUriName`  `accessPathName`  varchar(1024) NOT NULL DEFAULT '' ");
        $this->addSql("ALTER TABLE  `access_log` CHANGE  `accessUriMd5`  `accessSearch`  varchar(1024) NOT NULL DEFAULT '' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
