<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140510143309 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `user_state` CHANGE  `dayUserPv`  `dayActUserPv` int(10) NOT NULL DEFAULT '0'  COMMENT '日用户PV' AFTER `dayActUser` ");

        $this->addSql("ALTER TABLE  `guest_state` CHANGE  `dayGuestPv`  `dayActGuestPv` int(10) NOT NULL DEFAULT '0'  COMMENT '日游客PV' AFTER `dayActGuest` ");

        

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
