<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131125152141 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
       

        $this->addSql("ALTER TABLE  `activity` CHANGE  `experters`  `experters` text CHARACTER SET utf8 NOT NULL COMMENT '讲师Id' 
            ");

        $this->addSql("ALTER TABLE  `activity` CHANGE  `explain`  `outline` text CHARACTER SET utf8 NOT NULL COMMENT '简要描述' 
            ");

        $this->addSql("ALTER TABLE  `activity` CHANGE  `about`  `about` text CHARACTER SET utf8 NOT NULL COMMENT '详细描述'  AFTER  `outline` 
            ");
     

        $this->addSql("       
            ALTER TABLE  `activity` ADD  `summary`  text  CHARACTER SET utf8 COMMENT '会后总结'  AFTER  `about` 
            ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
