<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140128203358 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `sale_linksale` CHANGE  `adCommissionType`  `adCommissionType`  VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'ratio' COMMENT '佣金类型：ratio quota'  ");

         $this->addSql("ALTER TABLE  `sale_linksale` CHANGE  `reduceType`  `reduceType`  VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'ratio' COMMENT '让利类型：ratio quota'  ");

         $this->addSql("ALTER TABLE  `sale_offsale` CHANGE  `adCommissiontype`  `adCommissiontype`  VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'ratio' COMMENT '佣金类型：ratio quota'  ");

         $this->addSql("ALTER TABLE  `sale_offsale` CHANGE  `reduceType`  `reduceType`  VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'ratio' COMMENT '让利类型：ratio quota'  ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
