<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140515141107 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE `course` DROP `isLive`;");
        $this->addSql("ALTER TABLE `course` ADD `type` VARCHAR(255) NOT NULL DEFAULT 'normal' COMMENT '课程类型' AFTER `status`;");
        $this->addSql("ALTER TABLE `course` CHANGE `stuNumUpperLimit` `maxStudentNum` INT(11) NOT NULL DEFAULT '0' COMMENT '直播课程最大学员数上线';");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
