<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130814091600 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `course_note` CHANGE  `contentCount`  `length` INT( 5 ) NOT NULL COMMENT  '笔记内容的字数'");
    	$this->addSql("ALTER TABLE  `course_member` CHANGE  `notesNum`  `noteNum` TINYINT UNSIGNED NOT NULL COMMENT  '笔记数目'");
    	$this->addSql("ALTER TABLE  `course_member` CHANGE  `notesLastUpdateTime`  `noteLastUpdateTime` INT( 10 ) UNSIGNED NOT NULL COMMENT  '最新的笔记更新时间'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
