<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130814110859 extends AbstractMigration
{
    public function up(Schema $schema)
    {

        $this->addSql("
            ALTER TABLE  `navigation` CHANGE  `type`  `type` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  '类型';
            ");
        $this->addSql("
            ALTER TABLE  `navigation` CHANGE  `status`  `isOpen` ENUM(  '0',  '1' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '1' COMMENT '默认1，为开启';
            ");
        $this->addSql("
            ALTER TABLE  `navigation` CHANGE  `openNewWindow`  `isNewWin` ENUM(  '0',  '1' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '1' COMMENT  '默认为1,另开窗口';
            ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
