<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140125224457 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

          $this->addSql("ALTER TABLE  `offsale` ADD  `partnerId`   int(11)  NOT NULL COMMENT  '渠道ID'  AFTER  `valid` ");

          $this->addSql("ALTER TABLE  `offsale` ADD  `managerId`   int(11)  NOT NULL COMMENT  '管理ID'  AFTER  `partnerId` ");

          $this->addSql("
		    CREATE TABLE IF NOT EXISTS `offsale_apply` (
			  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
			  `prodType` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT '商品类型',
			  `prodId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品Id',
			  `prodName`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT '商品名称',
			 
			  `status` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT '申请状态',
			  
			  `userId` int(11) NOT NULL COMMENT '用户id',
			  `updatedTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
			  `createdTime` int(11) unsigned NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='推广表'  AUTO_INCREMENT=1;
		  ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
