<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131203151142 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSQL("
    		ALTER TABLE `user` DROP `trueName`;
    		");
    	$this->addSQL("
    		ALTER TABLE  `user_profile` ADD  `idcard` VARCHAR( 24 ) NOT NULL COMMENT  '身份证号码' AFTER  `truename`;
    		");
    	$this->addSQL("
    		ALTER TABLE  `user_approval` CHANGE  `trueName`  `truename` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT  '名称';
    		");
    	$this->addSQL("
    		ALTER TABLE  `user_approval` CHANGE  `idCard`  `idcard` VARCHAR( 24 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  '身份证号';
    		");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
