<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130926182914 extends AbstractMigration
{
    public function up(Schema $schema)
    {
       $this->addSql("
			CREATE TABLE IF NOT EXISTS `user_action` (
				  `id` int(11) NOT NULL AUTO_INCREMENT,
				  `userId` int(11) DEFAULT NULL COMMENT '用户ID',
				  `city` varchar(125) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户所在城市',
				  `requestTime` int(11) DEFAULT NULL COMMENT '请求时间',
				  `courseId` int(11) DEFAULT NULL COMMENT '课程ID',
				  `courseName` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '课程名子',
				  `chapterId` int(11) DEFAULT NULL COMMENT '章节ID',
				  `chapterName` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '章节名称',
				  `lessonId` int(11) DEFAULT NULL COMMENT '课时ID',
				  `lessonName` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '课时名称',
				  `OperaterType` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户操作',
				  `createTime` int(11) NOT NULL,
				  PRIMARY KEY (`id`)
				) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='用户行为' AUTO_INCREMENT=3;
       	");
       $this->addSql("
       		ALTER TABLE  `activity` ADD `onlineAddress` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '线上地址' ");

       $this->addSql("
       		ALTER TABLE  `activity` ADD `teacherPostNum` int(11) unsigned DEFAULT '0' COMMENT '老师回复数' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
