<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131004092711 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	$this->addSql("
					CREATE TABLE `installed_packages` (
						`id` int(11) NOT NULL AUTO_INCREMENT,
						`ename` varchar(255) NOT NULL COMMENT '包名称',
						`cname` varchar(255) NOT NULL,
						`version` varchar(255) NOT NULL COMMENT 'version',
						`installlog` text NOT NULL COMMENT '安装日志',
						`installTime` int(11) NOT NULL COMMENT '安装时间',
						`from` varchar(255) NOT NULL COMMENT '来源',
					PRIMARY KEY (`id`),
					UNIQUE KEY `cname` (`ename`)
					) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='已安装包' AUTO_INCREMENT=1 ;
					");

    	$this->addSql("
					CREATE TABLE `packages` (
						`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
						`ename` varchar(255) NOT NULL COMMENT '包名称',
						`cname` varchar(255) NOT NULL COMMENT '包中文名称',
						`fromVersion` varchar(255) DEFAULT NULL COMMENT '从哪个版本升级',
						`version` varchar(255) NOT NULL COMMENT '版本',
						`filename` varchar(255) NOT NULL COMMENT '压缩包文件名',
						`comments` text COMMENT '更新说明',
						`level` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '重要等级',
						`depends` text NOT NULL COMMENT '依赖包们及版本',
						`packType` tinyint(4) NOT NULL COMMENT '0:安装包；1:升级包',
						`createTime` int(11) NOT NULL COMMENT '发布时间',
					PRIMARY KEY (`id`),
					UNIQUE KEY `packname` (`ename`)
					) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='升级包' AUTO_INCREMENT=1 ;
					");

    	$this->addSql("
					CREATE TABLE `upgradeLogs` (
						`id` bigint(20) NOT NULL AUTO_INCREMENT,
						`operation` varchar(32) NOT NULL COMMENT 'check: 检查 upgrade:更新 install:安装',
						`packages` text COMMENT '已安装的版本',
						`packageId` int(11) DEFAULT NULL COMMENT '升级id',
						`fromv` varchar(255) DEFAULT NULL COMMENT '从某版本升级',
						`tov` varchar(255) DEFAULT NULL COMMENT '安装版本',
						`ip` varchar(32) NOT NULL COMMENT '来源ip',
						`host` varchar(255) DEFAULT NULL COMMENT '来源host',
						`logtime` int(11) NOT NULL COMMENT '日期',
						`ename` varchar(255) NOT NULL,
						`cname` varchar(255) NOT NULL,
					PRIMARY KEY (`id`)
					) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='更新日志' AUTO_INCREMENT=1 ;
					");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
