<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140225104858 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `user_profile` CHANGE  `id`  `id`  int(11) unsigned NOT NULL " );

        $this->addSql("ALTER TABLE  `user_profile` ADD  `birthday2`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '出生年月'  AFTER  `birthday`");


        $this->addSql("ALTER TABLE  `user_approval` ADD   `gender` enum('male','female','secret') NOT NULL DEFAULT 'secret'  COMMENT '性别'  AFTER  `truename`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `birthday2`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '出生年月'  AFTER  `gender`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `lastDegree`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '最高学历'  AFTER  `job`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `lastSchool`   VARCHAR( 500  ) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '最后毕业院校'  AFTER  `lastDegree`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `lastMajors`    VARCHAR( 500  ) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '所学专业'  AFTER  `lastSchool`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `educations`   TEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '教育经历'  AFTER  `lastMajors`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `careers`   TEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '工作经历'  AFTER  `educations`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `skills`   TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '擅长技能'  AFTER  `careers`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `purpose`   TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '求职需求'  AFTER  `skills`");

        $this->addSql("ALTER TABLE  `user_approval` ADD  `resume`   VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  DEFAULT  ''   COMMENT '简历'  AFTER  `skills`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
