<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140127140002 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `mysale` ADD  `reduceType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'quota' COMMENT '让利类型：ratio,quota'  AFTER  `adCommission`");

        $this->addSql("ALTER TABLE  `mysale` ADD  `reducePrice`   float(10,2)  NOT NULL COMMENT  '让利额度'  AFTER  `reduceType` ");      

        $this->addSql("ALTER TABLE  `offsale` ADD  `adCommissionType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'ratio' COMMENT '佣金类型：ratio,quota'  AFTER  `promoCode`");

        $this->addSql("ALTER TABLE  `offsale` ADD  `adCommission`   float(10,2)  NOT NULL COMMENT  '佣金额度'  AFTER  `adCommissionType` ");

        $this->addSql("ALTER TABLE  `offsale` ADD  `reduceType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'quota' COMMENT '让利类型：ratio,quota'  AFTER  `adCommissionType`");

        $this->addSql("RENAME TABLE  `mysale` TO  `sale_mysale` ;");

        $this->addSql("RENAME TABLE  `offsale` TO  `sale_offsale` ;");

        $this->addSql("RENAME TABLE  `mysale_commission` TO  `sale_commission` ;");

     

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
