<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140212144221 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `sale_linksale` ADD  `adCommissionDay`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '推广有效期'  AFTER  `adCommission`");

        $this->addSql("ALTER TABLE  `sale_linksale` ADD  `customized`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '定制化佣金：0 否， 1 是'  AFTER  `adCommissionDay`");

        $this->addSql("ALTER TABLE  `sale_offsale` ADD  `adCommissionDay`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '推广有效期'  AFTER  `adCommission`");

        $this->addSql("ALTER TABLE  `sale_offsale` ADD  `customized`   int( 11 )   NOT NULL DEFAULT  '0' COMMENT '定制化佣金：0 否， 1 是'  AFTER  `adCommissionDay`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
