<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131220004943 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `course_member` CHANGE  `deadline`  `deadline` INT UNSIGNED NOT NULL DEFAULT  '0'");
    	$this->addSql("ALTER TABLE  `course` CHANGE  `expiryDay`  `expiryDay` INT UNSIGNED NOT NULL DEFAULT  '0'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
