<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140116173341 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `test_paper_result` ADD  `objectiveScore` INT NOT NULL DEFAULT  '0' AFTER  `score`");
    	$this->addSql("ALTER TABLE  `test_paper_result` CHANGE  `rightItemCount`  `rightItemCount` INT( 11 ) NOT NULL DEFAULT  '0'");
    	$this->addSql("ALTER TABLE  `test_paper_result` CHANGE  `subjectiveScore`  `subjectiveScore` INT( 11 ) NOT NULL DEFAULT  '0'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
