<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140109131348 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `mysale` CHANGE  `mTookeen`  `mTookeen`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT 'mtookeen' ");
        
        $this->addSql("ALTER TABLE  `mysale_order` CHANGE  `mTookeen`  `mTookeen`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT 'mtookeen' ");

        $this->addSql("ALTER TABLE  `mysale_visitor` CHANGE  `mTookeen`  `mTookeen`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT 'mtookeen' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
