<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140505144428 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE `course` ADD `isLive` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否为直播课程' AFTER `status`;");
    	$this->addSql("ALTER TABLE `course` ADD `stuNumUpperLimit` INT NOT NULL DEFAULT '0' COMMENT '直播课程最大学员数上线' AFTER `isLive`;");
    	$this->addSql("ALTER TABLE `course_lesson` ADD `startTime` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '直播课时开始时间' AFTER `viewedNum`, ADD `endTime` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '直播课时结束时间' AFTER `startTime`;");
    	$this->addSql("ALTER TABLE `course_lesson` ADD `liveJoinedNum` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '直播课时加入人数' AFTER `endTime`;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
