<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140106153325 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `test_result` ADD  `status` ENUM(  'none',  'right',  'wrong',  'noanswer' ) NOT NULL DEFAULT  'none' AFTER  `userId`");
        $this->addSql("ALTER TABLE  `test_result` ADD  `questionId` INT NOT NULL AFTER  `userId`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
