<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131203095441 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSQL("
			CREATE TABLE IF NOT EXISTS `questions` (
			  `id` bigint(20) NOT NULL AUTO_INCREMENT,
			  `stem` text NOT NULL COMMENT '题干',
			  `score` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分数',
			  `questionType` enum('choice','single_choice','fill','material','essay',' determine') NOT NULL COMMENT '题目类型',
			  `answer` text NOT NULL COMMENT '参考答案',
			  `analysis` text COMMENT '解析',
			  `categoryId` int(11) NOT NULL DEFAULT '0' COMMENT '类别',
			  `difficulty` smallint(5) unsigned NOT NULL DEFAULT '3' COMMENT '难度 1～5，默认3',
			  `targetId` int(11) NOT NULL COMMENT '从属于',
			  `targetType` enum('lesson','course','subject') NOT NULL COMMENT '从属类型：课时、课程、科目',
			  `parentId` bigint(20) DEFAULT NULL COMMENT '材料父ID',
			  `finishedTimes` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '完成次数',
			  `passedTimes` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '成功次数',
			  `userId` int(11) NOT NULL COMMENT '用户id',
			  `updatedTime` int(11) NOT NULL COMMENT '更新时间',
			  `createdTime` int(11) NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='问题表' AUTO_INCREMENT=1 ;

			CREATE TABLE IF NOT EXISTS `question_category` (
			  `id` int(11) NOT NULL AUTO_INCREMENT,
			  `name` varchar(255) NOT NULL COMMENT '类别名称',
			  `targetId` int(11) NOT NULL COMMENT '从属课程、科目id',
			  `targetType` enum('course','subject') NOT NULL COMMENT '从属课程、科目',
			  `userId` int(11) NOT NULL COMMENT '操作用户',
			  `updatedTime` int(11) NOT NULL COMMENT '更新时间',
			  `createdTime` int(11) NOT NULL COMMENT '创建时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='题库类别表' AUTO_INCREMENT=1 ;

			CREATE TABLE IF NOT EXISTS `question_choice` (
			  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
			  `quesitonId` bigint(20) NOT NULL COMMENT 'quesitonId',
			  `content` text NOT NULL COMMENT 'content',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
        ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
