<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140716091348 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
    	"CREATE TABLE IF NOT EXISTS `user_field` (
		`id` int(10) unsigned NOT NULL,
		  `fieldName` varchar(100) NOT NULL DEFAULT '',
		  `title` varchar(1024) NOT NULL DEFAULT '',
		  `seq` int(10) unsigned NOT NULL,
		  `enabled` int(10) unsigned NOT NULL DEFAULT '0',
		  `createdTime` int(100) unsigned NOT NULL
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

		ALTER TABLE `user_field`
		 ADD PRIMARY KEY (`id`);

		ALTER TABLE `user_field`
		MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;

		ALTER TABLE `user`  ADD `intField1` INT(255) UNSIGNED NULL ,  ADD `intField2` INT(255) UNSIGNED NULL ,  ADD `intField3` INT(255) UNSIGNED NULL ,  ADD `intField4` INT(255) UNSIGNED NULL ,  ADD `intField5` INT(255) UNSIGNED NULL ;


		ALTER TABLE `user` ADD `dateField1` INT(255) UNSIGNED NULL , ADD `dateField2` INT(255) UNSIGNED NULL , ADD `dateField3` INT(255) UNSIGNED NULL , ADD `dateField4` INT(255) UNSIGNED NULL , ADD `dateField5` INT(255) UNSIGNED NULL ;


		ALTER TABLE `user` ADD `floatField1` FLOAT(10,2) UNSIGNED NULL , ADD `floatField2` FLOAT(10,2) UNSIGNED NULL , ADD `floatField3` FLOAT(10,2) UNSIGNED NULL , ADD `floatField4` FLOAT(10,2) UNSIGNED NULL , ADD `floatField5` FLOAT(10,2) UNSIGNED NULL ;


		ALTER TABLE `user` ADD `varcharField1` VARCHAR(1024) NULL , ADD `varcharField2` VARCHAR(1024) NULL , ADD `varcharField3` VARCHAR(1024) NULL , ADD `varcharField4` VARCHAR(1024) NULL , ADD `varcharField5` VARCHAR(1024) NULL ;


		ALTER TABLE `user` ADD `textField1` TEXT NULL , ADD `textField2` TEXT NULL , ADD `textField3` TEXT NULL , ADD `textField4` TEXT NULL , ADD `textField5` TEXT NULL , ADD `textField6` TEXT NULL , ADD `textField7` TEXT NULL , ADD `textField8` TEXT NULL , ADD `textField9` TEXT NULL , ADD `textField10` TEXT NULL ;


		");
        // this up() migration is autogenerated, please modify it to your needs

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
