<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140402123816 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("RENAME TABLE  `member` TO  `vip` ;");
        $this->addSql("RENAME TABLE  `member_history` TO  `vip_history` ;");
        $this->addSql("RENAME TABLE  `member_level` TO  `vip_level` ;");
        $this->addSql("ALTER TABLE  `vip_history` CHANGE  `boughtTime`  `boughtTime` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
        $this->addSql("ALTER TABLE  `vip_history` CHANGE  `boughtDuration`  `boughtDuration` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
        $this->addSql("ALTER TABLE  `vip_history` CHANGE  `deadline`  `deadline` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
        $this->addSql("ALTER TABLE  `vip_history` CHANGE  `levelId`  `levelId` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '会员类型'");
        $this->addSql("ALTER TABLE  `vip_history` CHANGE  `createdTime`  `createdTime` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
