<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131204143139 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSQL("
	    	RENAME TABLE  `edusoho`.`questions` TO  `edusoho`.`quiz_question`");
        
    	$this->addSQL("
    		RENAME TABLE  `edusoho`.`question_category` TO  `edusoho`.`quiz_question_category`");
    	
	    $this->addSQL("
	    	RENAME TABLE  `edusoho`.`question_choice` TO  `edusoho`.`quiz_question_choice`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
