<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131031170311 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
       
            ALTER TABLE  `activity` ADD  `income`  float(10,2) NOT NULL  DEFAULT '0' COMMENT  '总收入'  AFTER  `price`
            ");

        $this->addSql("
         
            ALTER TABLE  `activity` ADD  `hitNum` INT(10) NOT NULL  DEFAULT '0' COMMENT  '活动总计浏览人次'  AFTER  `studentNum`          
             ");
    

        $this->addSql("
          
            ALTER TABLE  `activity` ADD  `limitNum` INT(10) NOT NULL  DEFAULT '0' COMMENT  '最大人数,0或空表示不限人数'  AFTER  `studentNum`");

        $this->addSql("
            ALTER TABLE  `activity` CHANGE  `price`   `price` float(10,2) NOT NULL DEFAULT '0.00' COMMENT  '0表示免费 大于100,000,000表示多种票 大于0小于100,000,000单一票'  ");


        $this->addSql("
            
            ALTER TABLE  `activity_member` ADD  `orderId` INT(10) NOT NULL  DEFAULT '0' COMMENT  '订单Id'  AFTER  `userId`");

        $this->addSql("
           
            ALTER TABLE  `activity_member` ADD  `approvalStatus`  enum('pass','checking','refuse') NOT NULL DEFAULT 'pass' COMMENT '审核状态'  AFTER  `orderId`");

         $this->addSql("                
                CREATE TABLE IF NOT EXISTS `order_details` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                  `orderId` int(10) NOT NULL COMMENT '订单Id',
                  `prodType` varchar(1024) CHARACTER SET utf8 DEFAULT NULL COMMENT '商品类型',
                  `prodId` int(10) NOT NULL  DEFAULT '0' COMMENT '商品Id',
                  `prodName` varchar(1024) CHARACTER SET utf8 DEFAULT NULL COMMENT '商品名称',
                  `amount` int(10) NOT NULL  DEFAULT '1' COMMENT '购买数量',
                  `unitPrice` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
                  `comment` varchar(1024) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注说明',
                  `createdTime` int(10) unsigned NOT NULL COMMENT '创建时间',
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='订单明细' AUTO_INCREMENT=1 ;
                ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
