<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140509183150 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `business_state` ADD  `dayNewGuest`  int(10) NOT NULL DEFAULT '0'  COMMENT '新游客' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `dayNewGuestVisit`  int(10) NOT NULL DEFAULT '0'  COMMENT '新游客PV' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `dayOldGuest`  int(10) NOT NULL DEFAULT '0'  COMMENT '老游客' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `dayOldGuestVisit`  int(10) NOT NULL DEFAULT '0'  COMMENT '老游客PV' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `dayUser`  int(10) NOT NULL DEFAULT '0'  COMMENT '注册用户访问' ");

        $this->addSql("ALTER TABLE  `business_state` ADD  `dayUserVisit`  int(10) NOT NULL DEFAULT '0'  COMMENT '注册用户PV' ");


        $this->addSql("ALTER TABLE  `guest_state` ADD  `dayNewGuestPv`  int(10) NOT NULL DEFAULT '0'  COMMENT '新游客Pv' ");

        $this->addSql("ALTER TABLE  `guest_state` ADD  `dayOldGuest`  int(10) NOT NULL DEFAULT '0'  COMMENT '老游客' ");

        $this->addSql("ALTER TABLE  `guest_state` ADD  `dayOldGuestPv`  int(10) NOT NULL DEFAULT '0'  COMMENT '老游客PV' ");


        $this->addSql("ALTER TABLE  `user_state` ADD  `dayRegUserPv`  int(10) NOT NULL DEFAULT '0'  COMMENT '注册用户Pv' ");

        $this->addSql("ALTER TABLE  `user_state` ADD  `dayOldUser`  int(10) NOT NULL DEFAULT '0'  COMMENT '老用户' ");

        $this->addSql("ALTER TABLE  `user_state` ADD  `dayOldUserPv`  int(10) NOT NULL DEFAULT '0'  COMMENT '老用户PV' ");

        $this->addSql("ALTER TABLE  `business_state` CHANGE  `priceType`  `priceType`  enum('free','fee','none')  NOT NULL DEFAULT 'none'  COMMENT '是否收費' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
