<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140717093105 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
        "
        ALTER TABLE `user_profile` CHANGE `idcard` `idcard` VARCHAR(24) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '身份证号码';
        ALTER TABLE `user`
		  DROP `intField1`,
		  DROP `intField2`,
		  DROP `intField3`,
		  DROP `intField4`,
		  DROP `intField5`,
		  DROP `dateField1`,
		  DROP `dateField2`,
		  DROP `dateField3`,
		  DROP `dateField4`,
		  DROP `dateField5`,
		  DROP `floatField1`,
		  DROP `floatField2`,
		  DROP `floatField3`,
		  DROP `floatField4`,
		  DROP `floatField5`,
		  DROP `varcharField1`,
		  DROP `varcharField2`,
		  DROP `varcharField3`,
		  DROP `varcharField4`,
		  DROP `varcharField5`,
		  DROP `varcharField6`,
		  DROP `varcharField7`,
		  DROP `varcharField8`,
		  DROP `varcharField9`,
		  DROP `varcharField10`,
		  DROP `textField1`,
		  DROP `textField2`,
		  DROP `textField3`,
		  DROP `textField4`,
		  DROP `textField5`,
		  DROP `textField6`,
		  DROP `textField7`,
		  DROP `textField8`,
		  DROP `textField9`,
		  DROP `textField10`;
  		ALTER TABLE `user_profile`  ADD `intField1` INT(255) UNSIGNED NULL ,  ADD `intField2` INT(255) UNSIGNED NULL ,  ADD `intField3` INT(255) UNSIGNED NULL ,  ADD `intField4` INT(255) UNSIGNED NULL ,  ADD `intField5` INT(255) UNSIGNED NULL ;


		ALTER TABLE `user_profile` ADD `dateField1` INT(255) UNSIGNED NULL , ADD `dateField2` INT(255) UNSIGNED NULL , ADD `dateField3` INT(255) UNSIGNED NULL , ADD `dateField4` INT(255) UNSIGNED NULL , ADD `dateField5` INT(255) UNSIGNED NULL ;


		ALTER TABLE `user_profile` ADD `floatField1` FLOAT(10,2) UNSIGNED NULL , ADD `floatField2` FLOAT(10,2) UNSIGNED NULL , ADD `floatField3` FLOAT(10,2) UNSIGNED NULL , ADD `floatField4` FLOAT(10,2) UNSIGNED NULL , ADD `floatField5` FLOAT(10,2) UNSIGNED NULL ;


		ALTER TABLE `user_profile` ADD `varcharField1` VARCHAR(1024) NULL , ADD `varcharField2` VARCHAR(1024) NULL , ADD `varcharField3` VARCHAR(1024) NULL , ADD `varcharField4` VARCHAR(1024) NULL , ADD `varcharField5` VARCHAR(1024) NULL ;


		ALTER TABLE `user_profile` ADD `textField1` TEXT NULL , ADD `textField2` TEXT NULL , ADD `textField3` TEXT NULL , ADD `textField4` TEXT NULL , ADD `textField5` TEXT NULL , ADD `textField6` TEXT NULL , ADD `textField7` TEXT NULL , ADD `textField8` TEXT NULL , ADD `textField9` TEXT NULL , ADD `textField10` TEXT NULL ;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
