<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130905102029 extends AbstractMigration
{
    public function up(Schema $schema)
    {
    	$this->addSql("ALTER TABLE  `user` ADD  `promoted` TINYINT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `roles`");
    	$this->addSql("ALTER TABLE  `user` ADD  `promotedTime` INT UNSIGNED NOT NULL AFTER  `promoted`");
    	$this->addSql("ALTER TABLE  `user` CHANGE  `promoted`  `promoted` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '是否为推荐'");
    	$this->addSql("ALTER TABLE  `user` CHANGE  `promotedTime`  `promotedTime` INT( 10 ) UNSIGNED NOT NULL COMMENT  '推荐时间'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
