<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140114163940 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("ALTER TABLE  `mysale_commission` CHANGE  `status`  `status`  varchar(255) CHARACTER SET utf8 NOT NULL COMMENT '佣金状态 created 买家未付款不可提款, paid 买家已付款可提款, applying 正在申请提款,refused 拒绝提款,cancelled 已取消申请提款 moneydrawed 已提款 frozen 冻结状态' ");

         $this->addSql("ALTER TABLE  `mysale_commission` ADD  `orderPrice` float(10,2)  NOT NULL COMMENT  '实际成交金额'  AFTER  `orderSn` ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
