<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131127101337 extends AbstractMigration
{
    public function up(Schema $schema)
    {
		$this->addSQL("DROP TABLE `user_real_name_authentication`;");
		$this->addSQL("ALTER TABLE `user` DROP `HasRealNameAuthenticated`;"); 
		$this->addSQL("ALTER TABLE `user` ADD `trueName` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;");
    	$this->addSQL("ALTER TABLE  `user` ADD  `approvalTime` INT( 10 ) NOT NULL COMMENT  '认证时间';");
    	$this->addSQL("ALTER TABLE  `user` ADD  `approvalStatus` enum('unapprove','approving','approved','approve_fail') NOT NULL DEFAULT 'unapprove' COMMENT '认证状态';");
    	$this->addSQL("
    		CREATE TABLE `user_approval` (
			  `id` int(10) NOT NULL AUTO_INCREMENT,
			  `userId` int(10) NOT NULL COMMENT '用户ID',
			  `idCard` varchar(24) NOT NULL COMMENT '身份证号',
			  `faceImg` varchar(500) NOT NULL,
			  `backImg` varchar(500) NOT NULL,
			  `trueName` varchar(255) DEFAULT NULL COMMENT '名称',
			  `note` text COMMENT '认证信息',
			  `status` enum('unapprove','approving','approved','approve_fail') NOT NULL COMMENT '是否通过：1是 0否',
			  `operatorId` int(10) unsigned DEFAULT NULL COMMENT '审核人',
			  `createdTime` int(10) NOT NULL COMMENT '申请时间',
			  PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='用户认证表';");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
