<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131016074406 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
   //  	$this->addSql("
			// ALTER TABLE  `course_lesson` ADD  `mediaId` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '媒体文件ID(user_disk_file.id)' AFTER  `media` ,
			// ADD  `mediaSource` VARCHAR( 32 ) NOT NULL DEFAULT  '' COMMENT  '媒体文件来源(self:本站上传,youku:优酷)' AFTER  `mediaId` ,
			// ADD  `mediaName` VARCHAR( 255 ) NOT NULL DEFAULT  '' COMMENT  '媒体文件名称' AFTER  `mediaSource` ,
			// ADD  `mediaUri` VARCHAR( 1024 ) NOT NULL DEFAULT  '' COMMENT  '媒体文件资源名' AFTER  `mediaName`;
   //  	");

   //      $this->addSql("ALTER TABLE `course_lesson` DROP `media`;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
