<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140327155744 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql(" ALTER TABLE  `tag` ADD   `isStick` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否首页显示' ");

        $this->addSql(" ALTER TABLE  `tag` ADD   `stickSeq` INT unsigned NOT NULL DEFAULT '0' COMMENT '显示排序号' ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
