<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130807095737 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE  `course_member` ADD  `notesNum` TINYINT( 4 ) NOT NULL COMMENT  '笔记数目' AFTER  `learnedNum`;");
        $this->addSql("ALTER TABLE  `course_member` ADD  `notesLastUpdateTime` INT( 10 ) NOT NULL COMMENT  '最新的笔记更新时间' AFTER  `notesNum`;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
