<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130709094336 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE  `course` ADD  `lessonNum` INT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `price`;");
        $this->addSql("ALTER TABLE  `course_member` ADD  `learnedNum` INT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `userId`");
        $this->addSql("ALTER TABLE  `course_member` ADD  `isLearned` TINYINT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `learnedNum`");
        $this->addSql("ALTER TABLE `course_member` ADD UNIQUE (`courseId` , `userId`)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
