<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131105140524 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `upload_files` CHANGE  `targetType`  `targetType` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT  '目标类型';");
        $this->addSql("ALTER TABLE  `upload_files` CHANGE  `updatedUid`  `updatedUserId` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '更新用户名';");
        $this->addSql("ALTER TABLE  `upload_files` CHANGE  `createdUid`  `createdUserId` INT( 10 ) UNSIGNED NOT NULL ;");
        $this->addSql("ALTER TABLE  `upload_files` CHANGE  `ext`  `ext` VARCHAR( 12 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT  '后缀';");
        $this->addSql("ALTER TABLE  `upload_files` CHANGE  `canDownload`  `canDownload` TINYINT NOT NULL DEFAULT '0' COMMENT  '是否可下载';");
        $this->addSql("ALTER TABLE  `upload_files` ADD  `convertHash` VARCHAR( 256 ) NOT NULL DEFAULT  '' COMMENT '文件转换时的查询转换进度用的Hash值' AFTER  `size` ;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
