<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140508164404 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

         $this->addSql("

         	CREATE TABLE IF NOT EXISTS `access_log_history` (
				  `id` int(11) NOT NULL AUTO_INCREMENT,
				  `logId` int(11) NOT NULL ,
				  `guestId` int(11) NOT NULL DEFAULT '0' COMMENT '游客Id',
				  `userId` int(11) NOT NULL DEFAULT '0' COMMENT '用户Id',
				  `prodType` varchar(255) NOT NULL COMMENT '产品类型',
				  `prodName` varchar(255) NOT NULL COMMENT '产品名称',
				  `prodId` int(10) NOT NULL COMMENT '产品Id',
				  `accessHref` varchar(1024) NOT NULL DEFAULT '',
				  `accessPathName` varchar(1024) NOT NULL DEFAULT '',
				  `accessSearch` varchar(1024) NOT NULL DEFAULT '',
				  `createdIp` varchar(64) NOT NULL,
				  `createdTime` int(11) NOT NULL DEFAULT '0',
				  `mTookeen` varchar(255) NOT NULL,
				  `partnerId` int(10) NOT NULL COMMENT '渠道Id',
				   PRIMARY KEY (`id`)
				) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='页面PV记录流水历史表';

         	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
