<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140513001919 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `course_chapter` ADD  `parentId` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  'parentId大于０时为单元' AFTER  `courseId`");
        $this->addSql("ALTER TABLE  `course_chapter` ADD  `type` ENUM(  'chapter',  'unit' ) NOT NULL DEFAULT  'chapter' COMMENT  '章节类型：chapter为章节，unit为单元。' AFTER  `courseId`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
