<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140210144225 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `testpaper` ADD  `target` VARCHAR( 255 ) NOT NULL DEFAULT  '' AFTER  `targetType`");
        // $this->addSql("ALTER TABLE `testpaper` DROP `targetId`");
        // $this->addSql("ALTER TABLE `testpaper` DROP `targetType`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
