<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140401220029 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
            RENAME TABLE `course_order` TO `orders`;
            RENAME TABLE `course_order_log` TO `order_log`;
            RENAME TABLE `course_order_refund` TO `order_refund`;

            ALTER TABLE  `orders` CHANGE  `courseId`  `targetId` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0';
            ALTER TABLE  `orders` ADD  `targetType` VARCHAR( 64 ) NOT NULL DEFAULT  '' AFTER  `title`;
            ALTER TABLE  `orders` CHANGE  `price`  `amount` FLOAT( 10, 2 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '订单实付金额';
            ALTER TABLE  `orders` ADD  `data` TEXT NULL DEFAULT NULL COMMENT  '订单业务数据' AFTER  `note`;

            ALTER TABLE  `course_member` ADD  `levelId` INT NOT NULL COMMENT  '用户以会员的方式加入课程学员时的会员等级ID' AFTER  `deadline`;
            ALTER TABLE  `course_member` CHANGE  `levelId`  `levelId` INT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '用户以会员的方式加入课程学员时的会员ID';

            TRUNCATE `orders`;
            TRUNCATE `order_log`;
            TRUNCATE `order_refund`;

        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
