<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131105205422 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("       
            ALTER TABLE  `activity` ADD  `goals`  text  CHARACTER SET utf8 COMMENT '目标'  AFTER  `status` 
            ");

        $this->addSql("       
            ALTER TABLE  `activity` ADD  `audience`  text  CHARACTER SET utf8 COMMENT '对象'  AFTER  `goals`
            ");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
