<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130905232854 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `course` CHANGE  `startTime`  `recommended` TINYINT UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '是否为推荐课程'");
        $this->addSql("ALTER TABLE  `course` CHANGE  `endTime`  `recommendedTime` INT( 10 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '推荐时间'");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
