<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130704220958 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
			CREATE TABLE IF NOT EXISTS `course_lesson_learn` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `userId` int(10) unsigned NOT NULL,
			  `courseId` int(10) unsigned NOT NULL,
			  `lessonId` int(10) unsigned NOT NULL,
			  `status` enum('learning','finished') NOT NULL,
			  `startTime` int(10) unsigned NOT NULL DEFAULT '0',
			  `finishedTime` int(10) unsigned NOT NULL DEFAULT '0',
			  PRIMARY KEY (`id`),
			  UNIQUE KEY `userId_lessonId` (`userId`,`lessonId`),
			  KEY `userId_courseId` (`userId`,`courseId`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
    	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
