<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106171007 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql(" ALTER TABLE  `activity` ADD  `priceMode`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '免费' COMMENT  '线下价格模式:免费|单一价|多种价'  AFTER  `price`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
