<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140213152158 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `testpaper_item` CHANGE  `score`  `score` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '分值',CHANGE  `missScore`  `missScore` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0'");
    	$this->addSql("ALTER TABLE  `testpaper_result` CHANGE  `score`  `score` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '分数', CHANGE  `objectiveScore`  `objectiveScore` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0', CHANGE  `subjectiveScore`  `subjectiveScore` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0'");
    	$this->addSql("ALTER TABLE  `testpaper` CHANGE  `score`  `score` FLOAT( 10, 1 ) UNSIGNED NOT NULL DEFAULT  '0' COMMENT  '总分'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
