<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140128190411 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `sale_commission` ADD  `saleType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT '推广类型：linksale-course,linksale-web,offsale-course,offsale-web'  AFTER  `id`");

         $this->addSql("ALTER TABLE  `sale_commission` CHANGE  `mTookeen`  `saleTookeen`  VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  ''  COMMENT '推广码：mTookeen,promoCode'  AFTER  `saleId`");

         $this->addSql("ALTER TABLE  `sale_linksale` ADD  `saleType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT '推广类型：linksale-course,linksale-web'  AFTER  `id`");

         $this->addSql("ALTER TABLE  `sale_offsale` ADD  `saleType`   VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '' COMMENT '推广类型：offsale-course,offsale-web'  AFTER  `id`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
