<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140128204041 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `sale_linksale` CHANGE  `adCommission`  `adCommission`  float( 10,2)  NOT NULL DEFAULT  '0.00' ");

         $this->addSql("ALTER TABLE  `sale_linksale` CHANGE  `reducePrice`  `reducePrice`  float( 10,2)  NOT NULL DEFAULT  '0.00' ");

         $this->addSql("ALTER TABLE  `sale_offsale` CHANGE  `adCommission`  `adCommission`  float( 10,2)  NOT NULL DEFAULT  '0.00' ");

         $this->addSql("ALTER TABLE  `sale_offsale` CHANGE  `reducePrice`  `reducePrice`  float( 10,2)  NOT NULL DEFAULT  '0.00' ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
