<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130710145051 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `course_member` ADD  `seq` INT UNSIGNED NOT NULL DEFAULT  '0' AFTER  `isLearned`");
        $this->addSql("ALTER TABLE  `course` ADD  `teacherIds` TEXT NULL DEFAULT NULL AFTER  `about`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
