<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131031170311 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `activity` ADD  `income`  float(10,2) NOT NULL  DEFAULT '0' COMMENT  '总收入'  AFTER  `price`");

        $this->addSql("ALTER TABLE  `activity` ADD  `hitNum` INT(10) NOT NULL  DEFAULT '0' COMMENT  '活动总计浏览人次'  AFTER  `studentNum`");

        $this->addSql("ALTER TABLE  `activity` ADD  `payment`  enum('onliePay','livePay') NOT NULL DEFAULT '线上支付' COMMENT '支付方式'  AFTER  `price`");

        $this->addSql("ALTER TABLE  `activity` ADD  `needConfirm`  enum('yes','no') NOT NULL DEFAULT '不需要' COMMENT '报名需要审核'  AFTER  `price`");

        $this->addSql("ALTER TABLE  `activity` ADD  `limitNum` INT(10) NOT NULL  DEFAULT '0' COMMENT  '最大人数,0或空表示不限人数'  AFTER  `studentNum`");



        $this->addSql("ALTER TABLE  `activity_member` ADD  `orderId` INT(10) NOT NULL  DEFAULT '0' COMMENT  '订单Id'  AFTER  `userId`");

        $this->addSql("ALTER TABLE  `activity_member` ADD   `confirm`  enum('pass','待审核','refuse') NOT NULL DEFAULT '待审核' COMMENT '审核状态'  AFTER  `price`");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
