<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140124021614 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `quiz_question` CHANGE  `difficulty`  `difficulty` ENUM(  'simple',  'normal',  'difficulty' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'normal'");
        $this->addSql("RENAME TABLE  `quiz_question` TO  `question` ;");
        $this->addSql("RENAME TABLE  `quiz_question_category` TO  `question_category` ;");
        $this->addSql("DROP TABLE quiz_question_choice");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
