<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140227154951 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

         $this->addSql("
          
           INSERT INTO `file_group` (`id`, `name`, `code`, `public`) VALUES       			
       			(100, '用户私有文件', 'user_private', 0),
       			(101, '默认文件私有组', 'default_private', 0);
          	");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
