<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140312222056 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	  // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
            
            CREATE TABLE `article_category` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `name` varchar(255) NOT NULL COMMENT '栏目名称',
              `code` varchar(64) NOT NULL COMMENT 'URL目录名称',
              `weight` int(11) NOT NULL DEFAULT '0',
              `publishArticle` tinyint(3) DEFAULT NULL COMMENT '是否允许发布文章',
              `pagesize` int(11) NOT NULL DEFAULT '10',
              `seoTitle` varchar(255) DEFAULT '' COMMENT '栏目标题',
              `seoKeyword` varchar(255) DEFAULT NULL COMMENT 'SEO 关键字',
              `seoDesc` varchar(255) DEFAULT NULL COMMENT '栏目描述（SEO）',
              `published` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '是否启用（1：启用 0：停用)',
              `parentId` int(10) unsigned NOT NULL DEFAULT '0',
              `type` varchar(64) DEFAULT NULL COMMENT '栏目类型',
              `templateName` varchar(255) DEFAULT NULL COMMENT '模板设置',
              `urlNameRule` varchar(255) DEFAULT NULL COMMENT 'URL命名规则',
              `comment` varchar(255) DEFAULT NULL COMMENT '评论',
              PRIMARY KEY (`id`),
              UNIQUE KEY `uri` (`code`)
            ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

           CREATE TABLE `article` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `title` varchar(255) NOT NULL COMMENT '文章标题',
              `alias` varchar(255) DEFAULT NULL COMMENT '别名',
              `categoryId` int(10) NOT NULL COMMENT '栏目',
              `editor` enum('richeditor','none') NOT NULL DEFAULT 'richeditor' COMMENT '编辑器选择类型字段',
              `tagIds` tinytext COMMENT 'tag标签',
              `source` varchar(255) DEFAULT NULL COMMENT '来源',
              `sourceUrl` varchar(255) DEFAULT NULL COMMENT '来源URL',
              `publishedTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发布时间',
              `body` text,
              `picture` varchar(255) NOT NULL DEFAULT '',
              `template` varchar(255) NOT NULL DEFAULT '' COMMENT '模板',
              `status` enum('published','unpublished','trash') NOT NULL COMMENT '状态',
              `hits` int(10) unsigned NOT NULL DEFAULT '0',
              `featured` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '头条',
              `promoted` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '推荐',
              `sticky` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否置顶',
              `userId` int(10) unsigned NOT NULL,
              `createdTime` int(10) unsigned NOT NULL,
              `type` varchar(255) DEFAULT '',
              `isFirstThumbnail` tinyint(3) NOT NULL DEFAULT '1',
              `updated` int(10) unsigned NOT NULL,
              PRIMARY KEY (`id`)
            ) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
