<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140303113930 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
	        CREATE TABLE IF NOT EXISTS `delivery_setting` (
				  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
				  `deliverType` varchar(1024) NOT NULL COMMENT '服务角色:teacher(主教),assistant（助教）,headmaster（校长）,headman(班长)',
				  `delivererId` int(11) NOT NULL COMMENT '服务交付人Id',
				  `prodType` varchar(128) NOT NULL COMMENT '商品类型',
				  `prodId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品Id',
				  `prodName` varchar(1024) DEFAULT NULL COMMENT '商品名称',
				  `adCommissionType` varchar(64) NOT NULL DEFAULT 'ratio' COMMENT '佣金类型：ratio quota',
				  `adCommission` float(10,2) NOT NULL DEFAULT '0.00',
				  `adCommissionDay` int(11) NOT NULL DEFAULT '0' COMMENT '佣金有效期',
				  `customized` int(11) NOT NULL DEFAULT '0' COMMENT '定制化佣金：0 否， 1 是',
				  `updatedTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
				  `createdTime` int(11) unsigned NOT NULL COMMENT '创建时间',
				  `managerId` int(11) NOT NULL DEFAULT '0' COMMENT '管理人员Id',
	  				PRIMARY KEY (`id`)
			) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='服务交付佣金设置表' AUTO_INCREMENT=1;
		");

		$this->addSql("
	        CREATE TABLE IF NOT EXISTS `delivery_commission` (
				  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
				  `buyerIP` varchar(255) NOT NULL DEFAULT '' COMMENT '购买人IP',
				  `dcsId` int(11) NOT NULL COMMENT '服务交付佣金设置Id',
				  `deliverType` varchar(1024) NOT NULL COMMENT '服务角色:teacher(主教),assistant（助教）,headmaster（校长）,headman(班长)',
				  `buyerId` int(11) NOT NULL COMMENT '购买人Id',
				  `delivererId` int(11) NOT NULL COMMENT '服务交付人Id',
				  `orderId` int(11) NOT NULL COMMENT '订单Id',
				  `orderSn` varchar(255) NOT NULL COMMENT '订单sn',
				  `orderPrice` float(10,2) NOT NULL COMMENT '实际成交金额',
				  `commission` float(11,2) NOT NULL DEFAULT '0.00' COMMENT '本笔订单佣金收入',
				  `note` varchar(1024) DEFAULT NULL COMMENT '备注说明',
				  `status` varchar(255) NOT NULL COMMENT '佣金状态 created 买家未付款不可提款, paid 买家已付款可提款, applying 正在申请提款,refused 拒绝提款,cancelled 已取消申请提款 moneydrawed 已提款 frozen 冻结状态',
				  `updatedTime` int(11) NOT NULL DEFAULT '0' COMMENT '最后一次操作时间',
				  `drawedTime` int(11) NOT NULL DEFAULT '0' COMMENT '取款时间',
				  `paidTime` int(11) NOT NULL DEFAULT '0' COMMENT '订单支付时间',
				  `createdTime` int(11) NOT NULL COMMENT '创建时间',
				  PRIMARY KEY (`id`)
				) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='交付成本记录表' AUTO_INCREMENT=1;
		");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
