<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131006183702 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("
          DELETE FROM  `file_group` ;
          INSERT INTO `file_group` (`id`, `name`, `code`, `public`) VALUES
      			(1, '默认文件组', 'default', 1),
      			(2, '缩略图', 'thumb', 1),
      			(3, '课程', 'course', 1),
      			(4, '用户', 'user', 1),
      			(5, '课程私有文件', 'course_private', 0),
      			(6, '相册', 'photo', 1),
      			(7, '活动', 'activity', 1),
      			(8, '活动私有文件', 'activity_private', 0);
          INSERT INTO `location` (`id`, `parentId`, `name`, `pinyin`) VALUES
            (1, 0, '北京', 'beijing'),
            (2, 0, '上海', 'shanghai');
         	");


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
