<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131101145645 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql("ALTER TABLE  `course_order` ADD  `postAddress` VARCHAR( 1024 )  DEFAULT NULL COMMENT  '邮寄地址'  AFTER  `price`");

         $this->addSql("ALTER TABLE  `course_order` ADD  `postZip` VARCHAR( 24 )  DEFAULT NULL COMMENT  '邮编'  AFTER  `postAddress`");

         $this->addSql("ALTER TABLE  `course_order` ADD  `reciever` VARCHAR( 1024 )  DEFAULT NULL COMMENT  '收件人'  AFTER  `postZip`");

         $this->addSql("ALTER TABLE  `course_order` ADD  `invoice` VARCHAR( 1024 )  DEFAULT NULL COMMENT  '发票抬头'  AFTER  `reciever`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
