<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106153326 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
         $this->addSql(" ALTER TABLE  `activity` ADD  `payment`   VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '线上支付' COMMENT  '支付方式'  AFTER  `price`");

        $this->addSql("	ALTER TABLE  `activity` ADD  `needApproval`  VARCHAR( 255 )  CHARACTER SET utf8  DEFAULT '不需要' COMMENT  '是否需要审核'  AFTER  `price`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
