<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140429093606 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE  `user` ADD  `createdPartnerId`   int(11) NOT NULL DEFAULT '0'  COMMENT '注册渠道ID' ");
        $this->addSql("ALTER TABLE  `user` ADD  `loginPartnerId`  int(11) NOT NULL DEFAULT '0'  COMMENT '注册渠道ID' ");

        $this->addSql("ALTER TABLE  `guest` ADD  `createdPartnerId`   int(11) NOT NULL DEFAULT '0'  COMMENT '注册渠道ID' ");
        $this->addSql("ALTER TABLE  `guest` ADD  `lastAccessPartnerId`  int(11) NOT NULL DEFAULT '0'  COMMENT '最后访问渠道ID' ");

        $this->addSql("ALTER TABLE `access_log` DROP `partnerName`");

        $this->addSql("ALTER TABLE `access_log` DROP `nickname`");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
