<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140210232103 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->addSql("ALTER TABLE  `testpaper_item_result` CHANGE  `status`  `status` ENUM(  'none',  'right',  'partRight',  'wrong',  'noAnswer' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'none'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
