<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir   = dirname($vendorDir);

return array(
    'Twig_Extensions_'                      => array($vendorDir.'/twig/extensions/lib'),
    'Twig_'                                 => array($vendorDir.'/twig/twig/lib'),
    'Symfony\\'                             => array($vendorDir.'/symfony/symfony/src'),
    'Sensio\\Bundle\\GeneratorBundle'       => array($vendorDir.'/sensio/generator-bundle'),
    'Sensio\\Bundle\\DistributionBundle'    => array($vendorDir.'/sensio/distribution-bundle'),
    'SensioLabs\\Security'                  => array($vendorDir.'/sensiolabs/security-checker'),
    'Psr\\Log\\'                            => array($vendorDir.'/psr/log'),
    'Pimple'                                => array($vendorDir.'/pimple/pimple/lib'),
    'PHPExcel'                              => array($vendorDir.'/phpoffice/phpexcel/Classes'),
    'Asm89'                                 => array($vendorDir.'/asm89/twig-cache-extension/lib'),
    'Flexihash'                             => array($vendorDir.'/flexihash/flexihash/src'),
    'Imagine'                               => array($vendorDir.'/imagine/imagine/lib'),
    'HTMLPurifier'                          => array($vendorDir.'/ezyang/htmlpurifier/library'),
    'Doctrine\\ORM\\'                       => array($vendorDir.'/doctrine/orm/lib'),
    'Doctrine\\DBAL\\Migrations'            => array($vendorDir.'/doctrine/migrations/lib'),
    'Doctrine\\DBAL\\'                      => array($vendorDir.'/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\'             => array($vendorDir.'/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\'         => array($vendorDir.'/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\'       => array($vendorDir.'/doctrine/collections/lib'),
    'Doctrine\\Common\\Cache\\'             => array($vendorDir.'/doctrine/cache/lib'),
    'Doctrine\\Common\\Annotations\\'       => array($vendorDir.'/doctrine/annotations/lib'),
    'Doctrine\\Common\\'                    => array($vendorDir.'/doctrine/common/lib'),
    'Doctrine\\Bundle\\MigrationsBundle'    => array($vendorDir.'/doctrine/doctrine-migrations-bundle'),
    'Doctrine\\Bundle\\DoctrineCacheBundle' => array($vendorDir.'/doctrine/doctrine-cache-bundle'),
    'Assetic'                               => array($vendorDir.'/kriswallsmith/assetic/src'),
    ''                                      => array($baseDir.'/src', $baseDir.'/plugins'),
    'Mockery'                               => array($vendorDir.'/mockery/mockery/library')
);
